--ELIMINACION DE SESIONES
SELECT 'ALTER SYSTEM KILL SESSION '||
       CHR(39)||TO_CHAR(SID)||','||TO_CHAR(SERIAL#)||CHR(39)||';'
  FROM V$SESSION
 WHERE USERNAME='&&ESQUEMA';

--CONSTRUCCION DE SENTENCIAS DE ELIMINACION DE OBJETOS
SELECT 'DROP TABLE ' || owner || '.' || table_name || ' CASCADE CONSTRAINTS;' 
FROM dba_tables 
WHERE owner IN ( '&&ESQUEMA' )
UNION
SELECT 'DROP SEQUENCE ' || SEQUENCE_OWNER || '.' || SEQUENCE_NAME ||';'
FROM DBA_SEQUENCES
WHERE SEQUENCE_OWNER IN ('&&ESQUEMA')
UNION
SELECT 'DROP PROCEDURE ' || OWNER || '.' || OBJECT_NAME || ';' 
FROM DBA_OBJECTS
WHERE OBJECT_TYPE LIKE '%PROCEDURE%' AND  OWNER IN ( '&&ESQUEMA' )
UNION
SELECT 'DROP PACKAGE ' || OWNER || '.' || OBJECT_NAME || ';' 
FROM DBA_OBJECTS
WHERE OBJECT_TYPE LIKE '%PACKAGE%' AND  OWNER IN ( '&&ESQUEMA' )
UNION
SELECT 'DROP FUNCTION ' || OWNER || '.' || OBJECT_NAME || ';' 
FROM DBA_OBJECTS
WHERE OBJECT_TYPE LIKE '%FUNCTION%' AND  OWNER IN ( '&&ESQUEMA' )
UNION
SELECT 'DROP VIEW ' || OWNER || '.' || VIEW_NAME || ';'
FROM DBA_VIEWS
WHERE OWNER='&&ESQUEMA'
UNION
SELECT 'DROP TYPE '||OWNER||'.'||TYPE_NAME||';' 
FROM DBA_TYPES 
WHERE OWNER = '&&ESQUEMA';

--COMANDO DE SALIDA
SELECT 'EXIT;' FROM DUAL;
